// Hangy — Design System · seção "Icons (Lucide)" da página Components do Figma.
//
// Contrato: a lista abaixo é fechada e espelha exatamente os 39 símbolos
// `Icon/<nome-lucide>` do Figma. Não adicione um ícone aqui sem alinhar com
// design — a lista do Figma é a fonte da verdade.
//
// A chave é o nome lucide em kebab-case (igual ao Figma); o valor é o
// componente correspondente de `lucide-react-native`.

import {
  ArrowLeft,
  Bell,
  Calendar,
  CalendarX,
  Camera,
  Check,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  Clock,
  Compass,
  Eye,
  EyeOff,
  Flag,
  House,
  Image,
  Info,
  Lock,
  Mail,
  MapPin,
  MapPinOff,
  Pencil,
  Plus,
  Radio,
  Search,
  SearchX,
  Settings,
  Share,
  Share2,
  SlidersHorizontal,
  Star,
  Store,
  Ticket,
  Trash2,
  TriangleAlert,
  User,
  Users,
  X,
} from 'lucide-react-native';

export const icons = {
  'arrow-left': ArrowLeft,
  bell: Bell,
  calendar: Calendar,
  'calendar-x': CalendarX,
  camera: Camera,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  clock: Clock,
  compass: Compass,
  eye: Eye,
  'eye-off': EyeOff,
  flag: Flag,
  house: House,
  image: Image,
  info: Info,
  lock: Lock,
  mail: Mail,
  'map-pin': MapPin,
  'map-pin-off': MapPinOff,
  pencil: Pencil,
  plus: Plus,
  radio: Radio,
  search: Search,
  'search-x': SearchX,
  settings: Settings,
  share: Share,
  'share-2': Share2,
  'sliders-horizontal': SlidersHorizontal,
  star: Star,
  store: Store,
  ticket: Ticket,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  user: User,
  users: Users,
  x: X,
} as const;
